cursomain_homepage:
    path:     /
    defaults: { _controller: CursomainBundle:Default:index }

cursomain_help:
    path:     /ayuda/{tema}
    defaults: { _controller: CursomainBundle:Default:ayuda }

cursomain_nosotros:
    path:     /nosotros/{nombre}/{apellidos}/{nacimiento}
    defaults: { _controller: CursomainBundle:Info:nosotros, nombre:Majid, apellidos:BERKANE, nacimiento:Nador }

cursomain_info:
    path:     /info/{pagina}
    defaults: { _controller: CursomainBundle:Info:pagina_estatica, pagina:quien }


curso_main_newProd:
    path:     /productos/nuevoProducto
    defaults: { _controller: CursomainBundle:Product:nuevoProducto }

