<?php

namespace Test\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * marcas_autosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class marcas_autosRepository extends EntityRepository
{
}
