<?php

namespace Test\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * t_carroceria_motoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class t_carroceria_motoRepository extends EntityRepository
{
}
