<?php

namespace Test\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * t_rubica_barcosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class t_rubica_barcosRepository extends EntityRepository
{
}
