<?php

namespace Test\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * t_vehi_aduanasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class t_vehi_aduanasRepository extends EntityRepository
{
}
